apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-volume
  labels:
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/data/html"
---
